/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#faf9ff",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#edf0ff",
        "inverse-primary": "#b2c5ff",
        "inverse-surface": "#1d3054",
        "on-background": "#051a3e",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-primary-container": "#c4d2ff",
        "on-primary-fixed": "#001848",
        "on-primary-fixed-variant": "#0040a2",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#475a7e",
        "on-secondary-fixed": "#041b3c",
        "on-secondary-fixed-variant": "#34476a",
        "on-surface": "#051a3e",
        "on-surface-variant": "#434654",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#c3d3f5",
        "on-tertiary-fixed": "#091c35",
        "on-tertiary-fixed-variant": "#374763",
        outline: "#737685",
        "outline-variant": "#c3c6d6",
        primary: "#003d9b",
        "primary-container": "#0052cc",
        "primary-fixed": "#dae2ff",
        "primary-fixed-dim": "#b2c5ff",
        secondary: "#4c5e83",
        "secondary-container": "#bfd2fd",
        "secondary-fixed": "#d7e2ff",
        "secondary-fixed-dim": "#b4c7f1",
        surface: "#faf9ff",
        "surface-bright": "#faf9ff",
        "surface-container": "#e9edff",
        "surface-container-high": "#e1e8ff",
        "surface-container-highest": "#d8e2ff",
        "surface-container-low": "#f1f3ff",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#ccdaff",
        "surface-tint": "#0c56d0",
        "surface-variant": "#d8e2ff",
        tertiary: "#34445f",
        "tertiary-container": "#4b5b78",
        "tertiary-fixed": "#d6e3ff",
        "tertiary-fixed-dim": "#b7c7e8"
      },
      fontFamily: {
        display: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
