version: '3.8'

networks:
  hr-network:
    driver: bridge

services:
  hrms-frontend:
    build:
      context: ./Frontend
      dockerfile: ./Dockerfile
    container_name: hrms-frontend
    ports:
      - "82:80"
    depends_on:
      - hr-system-api
    networks:
      - hr-network

  hr-system-api:
    build:
      context: .
      dockerfile: ./Backend/dockerfile
    container_name: hr-system-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__sqlConnection=Server=sqlserver,1433;Database=CompanyEmployeesDB;User Id=sa;Password=YourStrong@Password123;Encrypt=false;TrustServerCertificate=true;
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - hr-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password123
    volumes:
      - sqlserver-db:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "YourStrong@Password123" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - hr-network

volumes:
  sqlserver-db: